### ISSUE TITLE
Saving layouts

### ISSUE THREAD

**Issue by MichaelPHStumpf** [abhijithanilkumar/VisJS.jl#4]
Is there a way to store a layout? I need to plot (and compare) several networks among the same set of nodes and would like to keep the same node positions. Would this require digging deeper into vis.js?

**Comment by abhijithanilkumar** [comment]
Well, I'm sorry that is not possible with the current state of VisJS.jl. Currently, it just spits out JS code and communication from JS back to Julia isn't possible. Therefore, this package cannot be used for your use case.
